"use strict";

// tests for addProduct
// Generated by serverless-mocha-plugin

const mochaPlugin = require("serverless-mocha");
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper(
  "addProduct",
  "../../../src/functions/addProduct.js",
  "addProduct"
);
const AWS = require("aws-sdk-mock");
const AWS_SDK = require("aws-sdk");
AWS.setSDKInstance(AWS_SDK);

describe("addProduct", () => {
  before((done) => {
    done();
  });

  it("implement tests here", async () => {
    const response = await wrapped.run({});
    expect(response).to.not.be.empty;
  });
});
